import React from 'react';
import { FileText, Download, Calendar, Filter, FileSpreadsheet, File } from 'lucide-react';

const mockReports = [
    { id: 1, name: 'Daily Health Summary - 24 Oct 2025', type: 'PDF', size: '2.4 MB', generated: 'Today, 08:00 AM' },
    { id: 2, name: 'Weekly Environmental Audit', type: 'CSV', size: '156 KB', generated: '23 Oct 2025' },
    { id: 3, name: 'Traceability Log Export (Batch A)', type: 'JSON', size: '4.1 MB', generated: '21 Oct 2025' },
    { id: 4, name: 'Disease Risk Analysis Q3', type: 'PDF', size: '8.2 MB', generated: '01 Oct 2025' },
    { id: 5, name: 'Livestock Inventory Report', type: 'PDF', size: '1.2 MB', generated: '01 Oct 2025' },
];

const ReportsView: React.FC = () => {
  return (
    <div className="space-y-6">
        <div className="flex justify-between items-center">
             <div className="bg-slate-800 border border-slate-700 rounded-lg p-1 flex">
                <button className="px-4 py-2 bg-slate-700 text-white rounded-md text-sm font-medium shadow-sm">All Reports</button>
                <button className="px-4 py-2 text-slate-400 hover:text-white rounded-md text-sm font-medium transition-colors">Generated by Me</button>
                <button className="px-4 py-2 text-slate-400 hover:text-white rounded-md text-sm font-medium transition-colors">Scheduled</button>
             </div>
             
             <button className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg font-medium text-sm shadow-lg shadow-blue-500/20 transition-all flex items-center gap-2">
                <FileText className="w-4 h-4" />
                Generate New Report
             </button>
        </div>

        <div className="bg-slate-800 border border-slate-700 rounded-xl shadow-lg overflow-hidden">
             <table className="w-full text-left border-collapse">
                <thead>
                    <tr className="bg-slate-900/50 border-b border-slate-700 text-slate-400 text-xs uppercase tracking-wider">
                        <th className="p-4 font-semibold">Report Name</th>
                        <th className="p-4 font-semibold">Type</th>
                        <th className="p-4 font-semibold">Size</th>
                        <th className="p-4 font-semibold">Date Generated</th>
                        <th className="p-4 font-semibold text-right">Action</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-slate-700/50">
                    {mockReports.map((report) => (
                        <tr key={report.id} className="hover:bg-slate-700/30 transition-colors">
                            <td className="p-4">
                                <div className="flex items-center gap-3">
                                    <div className={`p-2 rounded-lg ${
                                        report.type === 'PDF' ? 'bg-rose-500/20 text-rose-400' : 
                                        report.type === 'CSV' ? 'bg-emerald-500/20 text-emerald-400' :
                                        'bg-slate-500/20 text-slate-400'
                                    }`}>
                                        {report.type === 'PDF' ? <FileText className="w-5 h-5" /> : 
                                         report.type === 'CSV' ? <FileSpreadsheet className="w-5 h-5" /> :
                                         <File className="w-5 h-5" />}
                                    </div>
                                    <span className="font-medium text-slate-200">{report.name}</span>
                                </div>
                            </td>
                            <td className="p-4">
                                <span className="text-xs font-bold bg-slate-900 text-slate-400 px-2 py-1 rounded border border-slate-700">{report.type}</span>
                            </td>
                            <td className="p-4 text-sm text-slate-400 font-mono">{report.size}</td>
                            <td className="p-4 text-sm text-slate-400 flex items-center gap-2">
                                <Calendar className="w-3.5 h-3.5" />
                                {report.generated}
                            </td>
                            <td className="p-4 text-right">
                                <button className="text-blue-400 hover:text-white p-2 hover:bg-blue-600 rounded-lg transition-colors" title="Download">
                                    <Download className="w-4 h-4" />
                                </button>
                            </td>
                        </tr>
                    ))}
                </tbody>
             </table>
        </div>
    </div>
  );
};

export default ReportsView;